spring.application.name=backend
server.servlet.context-path=/backend
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=library_management;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.data.jpa.repositories.enabled=true
server.port=8080